import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

const projectRoot = path.resolve(__dirname, '../../');
const userGuidePath = path.join(projectRoot, 'USER_GUIDE.md');
const userGuideContent = fs.readFileSync(userGuidePath, 'utf8');

describe('Milestone 4: USER_GUIDE.md AGENTS.md Compliance & Integrity', () => {
  describe('1. Prohibited Marketing Terms Audit', () => {
    const bannedTerms = [
      '本地',
      '免费',
      '开源',
      '不上传',
      '无需上传',
      '不用上传',
      '零上传',
      '私密',
      '隐私保护'
    ];

    bannedTerms.forEach(term => {
      it(`must NOT contain banned marketing term: "${term}"`, () => {
        const matches = [...userGuideContent.matchAll(new RegExp(term, 'g'))];
        expect(matches.length, `Found banned term "${term}" in USER_GUIDE.md`).toBe(0);
      });
    });
  });

  describe('2. Automated Generative Badges & Watermarks Audit', () => {
    const generativeBadges = [
      'ai-generated',
      'powered by',
      'generated by',
      'chatgpt',
      'openai',
      'claude',
      'deepseek',
      'gemini',
      'copilot',
      'ai生成',
      '由ai生成',
      '由 ai 生成',
      '人工智能生成'
    ];

    generativeBadges.forEach(badge => {
      it(`must NOT contain generative badge / marketing claim: "${badge}"`, () => {
        const matches = [...userGuideContent.matchAll(new RegExp(badge, 'gi'))];
        expect(matches.length, `Found generative badge "${badge}" in USER_GUIDE.md`).toBe(0);
      });
    });
  });

  describe('3. Section 5b Absence and Numbering Sequence', () => {
    it('must NOT contain Section 5b heading or references', () => {
      const match5b = [...userGuideContent.matchAll(/5b/gi)];
      expect(match5b.length, 'Found "5b" in USER_GUIDE.md').toBe(0);
    });

    it('must have sequential section numbering from 1 to 10', () => {
      const sectionHeadingRegex = /^##\s+([0-9]+)\.\s+(.+)$/gm;
      const sections: { num: number; title: string }[] = [];
      let m;
      while ((m = sectionHeadingRegex.exec(userGuideContent)) !== null) {
        sections.push({ num: parseInt(m[1], 10), title: m[2].trim() });
      }

      expect(sections.length).toBe(10);
      for (let i = 0; i < 10; i++) {
        expect(sections[i].num).toBe(i + 1);
      }
      expect(sections[0].title).toContain('界面结构');
      expect(sections[1].title).toContain('通用操作');
      expect(sections[2].title).toContain('图片');
      expect(sections[3].title).toContain('PDF');
      expect(sections[4].title).toContain('音频');
      expect(sections[5].title).toContain('视频');
      expect(sections[6].title).toContain('文档 / 数据 / 开发');
      expect(sections[7].title).toContain('键盘');
      expect(sections[8].title).toContain('故障排查');
      expect(sections[9].title).toContain('变更同步清单');
    });
  });

  describe('4. Broken Anchors and Invalid References', () => {
    it('verifies all Markdown links have valid targets', () => {
      const linkRegex = /\[([^\]]+)\]\(([^)]*)\)/g;
      let m;
      const links: { text: string; target: string }[] = [];
      while ((m = linkRegex.exec(userGuideContent)) !== null) {
        links.push({ text: m[1], target: m[2] });
      }

      // If internal anchor links exist, verify target exists
      for (const link of links) {
        if (link.target.startsWith('#')) {
          const anchor = link.target.slice(1);
          // Check if anchor or heading exists
          const escaped = anchor.replace(/-/g, '[-\\s]');
          const found = new RegExp(escaped, 'i').test(userGuideContent);
          expect(found, `Broken internal anchor link: ${link.target}`).toBe(true);
        }
      }
    });

    it('verifies referenced specification files exist in repository', () => {
      const referencedFiles = ['FEATURES.md', 'INTERACTION.md'];
      for (const file of referencedFiles) {
        const filePath = path.join(projectRoot, file);
        expect(fs.existsSync(filePath), `Referenced file does not exist: ${file}`).toBe(true);
      }
    });
  });

  describe('5. Full 51 Tools Documentation Coverage', () => {
    it('documents all 51 registered tools with backticked IDs', () => {
      const registryPath = path.join(projectRoot, 'src/tools/registry.ts');
      const registryContent = fs.readFileSync(registryPath, 'utf8');
      const toolMatches = [...registryContent.matchAll(/'([a-z0-9-]+)':\s*\{/g)].map(m => m[1]);

      expect(toolMatches.length).toBe(51);

      const missingTools: string[] = [];
      for (const id of toolMatches) {
        if (!userGuideContent.includes('`' + id + '`')) {
          missingTools.push(id);
        }
      }

      expect(missingTools, `Missing tools in USER_GUIDE.md: ${missingTools.join(', ')}`).toEqual([]);
    });
  });
});
